<a href="https://colab.research.google.com/github/mnoorchenar/Grading_2251Course/blob/main/Grading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# import os
# os.getcwd()

import pandas as pd

Student_OWL = pd.read_csv("list_student_OWL.csv")
Student_OWL = Student_OWL.iloc[:,:3]
Student_OWL.head()

  Student ID              Name  # Student Number
0      kagne    Agne, Khennery         251221504
1   malhanaf  Al-Hanafi, Malak         251142157
2    marif27      Arif, Mariam         251239114
3    obhatt3         Bhatt, Om         251256665
4   jcamill5   Camillo, Joshua         251199106